services:
  - type: web
    name: oxin-crypto-mining
    env: python
    buildCommand: pip install -r pyproject.toml
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: SESSION_SECRET
        generateValue: true
      - key: FLASK_ENV
        value: production
  - type: pserv
    name: oxin-postgres
    env: postgresql
    plan: starter
    databaseName: oxin_db
    databaseUser: oxin_user